# Generated by Django 5.2.5 on 2025-10-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaWorkspaces',
            fields=[
                ('id_ws', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrupoUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('perfil', models.CharField(choices=[('Viewer', 'Viewer'), ('Member', 'Member'), ('Contributor', 'Contributor'), ('Admin', 'Admin')], default='Viewer')),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('name', models.ManyToManyField(to='restapp.listaworkspaces')),
            ],
        ),
    ]
