# Generated by Django 5.2.5 on 2025-10-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaUserWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_workspace', models.CharField(max_length=50)),
                ('workspace_name', models.CharField(max_length=150)),
                ('groupuseraccess', models.CharField(max_length=50)),
                ('displayname', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200)),
                ('principaltype', models.CharField(max_length=50)),
                ('emailaddress', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['displayname'],
            },
        ),
    ]
